//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GamerDnaMediaDownloader
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LocalCacheEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LocalCacheEntities object using the connection string found in the 'LocalCacheEntities' section of the application configuration file.
        /// </summary>
        public LocalCacheEntities() : base("name=LocalCacheEntities", "LocalCacheEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LocalCacheEntities object.
        /// </summary>
        public LocalCacheEntities(string connectionString) : base(connectionString, "LocalCacheEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LocalCacheEntities object.
        /// </summary>
        public LocalCacheEntities(EntityConnection connection) : base(connection, "LocalCacheEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaInfo> MediaInfoes
        {
            get
            {
                if ((_MediaInfoes == null))
                {
                    _MediaInfoes = base.CreateObjectSet<MediaInfo>("MediaInfoes");
                }
                return _MediaInfoes;
            }
        }
        private ObjectSet<MediaInfo> _MediaInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProcessionStatu> ProcessionStatus
        {
            get
            {
                if ((_ProcessionStatus == null))
                {
                    _ProcessionStatus = base.CreateObjectSet<ProcessionStatu>("ProcessionStatus");
                }
                return _ProcessionStatus;
            }
        }
        private ObjectSet<ProcessionStatu> _ProcessionStatus;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaInfoes(MediaInfo mediaInfo)
        {
            base.AddObject("MediaInfoes", mediaInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProcessionStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcessionStatus(ProcessionStatu processionStatu)
        {
            base.AddObject("ProcessionStatus", processionStatu);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalCacheModel", Name="MediaInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaInfo object.
        /// </summary>
        /// <param name="mediaPageUrl">Initial value of the MediaPageUrl property.</param>
        /// <param name="processed">Initial value of the Processed property.</param>
        /// <param name="saved">Initial value of the Saved property.</param>
        public static MediaInfo CreateMediaInfo(global::System.String mediaPageUrl, global::System.Boolean processed, global::System.Boolean saved)
        {
            MediaInfo mediaInfo = new MediaInfo();
            mediaInfo.MediaPageUrl = mediaPageUrl;
            mediaInfo.Processed = processed;
            mediaInfo.Saved = saved;
            return mediaInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaPageUrl
        {
            get
            {
                return _MediaPageUrl;
            }
            set
            {
                if (_MediaPageUrl != value)
                {
                    OnMediaPageUrlChanging(value);
                    ReportPropertyChanging("MediaPageUrl");
                    _MediaPageUrl = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MediaPageUrl");
                    OnMediaPageUrlChanged();
                }
            }
        }
        private global::System.String _MediaPageUrl;
        partial void OnMediaPageUrlChanging(global::System.String value);
        partial void OnMediaPageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MediaUrl
        {
            get
            {
                return _MediaUrl;
            }
            set
            {
                OnMediaUrlChanging(value);
                ReportPropertyChanging("MediaUrl");
                _MediaUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MediaUrl");
                OnMediaUrlChanged();
            }
        }
        private global::System.String _MediaUrl;
        partial void OnMediaUrlChanging(global::System.String value);
        partial void OnMediaUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocalFilename
        {
            get
            {
                return _LocalFilename;
            }
            set
            {
                OnLocalFilenameChanging(value);
                ReportPropertyChanging("LocalFilename");
                _LocalFilename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocalFilename");
                OnLocalFilenameChanged();
            }
        }
        private global::System.String _LocalFilename;
        partial void OnLocalFilenameChanging(global::System.String value);
        partial void OnLocalFilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private global::System.Boolean _Processed;
        partial void OnProcessedChanging(global::System.Boolean value);
        partial void OnProcessedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Saved
        {
            get
            {
                return _Saved;
            }
            set
            {
                OnSavedChanging(value);
                ReportPropertyChanging("Saved");
                _Saved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saved");
                OnSavedChanged();
            }
        }
        private global::System.Boolean _Saved;
        partial void OnSavedChanging(global::System.Boolean value);
        partial void OnSavedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalCacheModel", Name="ProcessionStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProcessionStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessionStatu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="lastMediaListPage">Initial value of the LastMediaListPage property.</param>
        /// <param name="finished">Initial value of the Finished property.</param>
        public static ProcessionStatu CreateProcessionStatu(global::System.Byte id, global::System.Int32 lastMediaListPage, global::System.Boolean finished)
        {
            ProcessionStatu processionStatu = new ProcessionStatu();
            processionStatu.Id = id;
            processionStatu.LastMediaListPage = lastMediaListPage;
            processionStatu.Finished = finished;
            return processionStatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Byte _Id;
        partial void OnIdChanging(global::System.Byte value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LastMediaListPage
        {
            get
            {
                return _LastMediaListPage;
            }
            set
            {
                OnLastMediaListPageChanging(value);
                ReportPropertyChanging("LastMediaListPage");
                _LastMediaListPage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastMediaListPage");
                OnLastMediaListPageChanged();
            }
        }
        private global::System.Int32 _LastMediaListPage;
        partial void OnLastMediaListPageChanging(global::System.Int32 value);
        partial void OnLastMediaListPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Finished
        {
            get
            {
                return _Finished;
            }
            set
            {
                OnFinishedChanging(value);
                ReportPropertyChanging("Finished");
                _Finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Finished");
                OnFinishedChanged();
            }
        }
        private global::System.Boolean _Finished;
        partial void OnFinishedChanging(global::System.Boolean value);
        partial void OnFinishedChanged();

        #endregion
    
    }

    #endregion
    
}
